### ISSUE TITLE
Uninitialized Unique Transaction Map

### ISSUE THREAD

**Issue by 0xJchen** [flashbots/mempool-dumpster#12]
```
➜  mempool-dumpster git:(main) ✗ go run cmd/collect/main.go -out ./out -nodes ws://127.0.0.1:23456
2023-09-09T05:15:48.979Z        INFO    Starting mempool-collector      {"version": "dev", "outDir": "./out", "uid": "Wxxp6T"}                                                                                   2023-09-09T05:15:48.979Z        INFO    connecting to node...   {"src": "ws://127.0.0.1:23456", "uri": "ws://127.0.0.1:23456"}                                                                                   2023-09-09T05:15:48.981Z        INFO    connection successful   {"src": "ws://127.0.0.1:23456", "uri": "ws://127.0.0.1:23456"}                                                                                   debug 0  map[]
Debug 1  ws://127.0.0.1:23456 0xae19eb962c1a06e48005fae3bf41e9e130c80ce62410dff8874e6234cbbadc6e map[]
panic: assignment to entry in nil map

goroutine 6 [running]:
github.com/flashbots/mempool-dumpster/collector.(*TxProcessor).processTx(0xc0002340f0, {{0xf6f735d, 0xedc8df685, 0x0}, 0xc000380180, {0x7ffca1651621, 0x14}})                                                            /home/ubuntu/tools/mempool-dumpster/collector/tx_processor.go:90 +0x585
github.com/flashbots/mempool-dumpster/collector.(*TxProcessor).Start(0xc0002340f0)
        /home/ubuntu/tools/mempool-dumpster/collector/tx_processor.go:76 +0x1e8
created by github.com/flashbots/mempool-dumpster/collector.Start in goroutine 1
        /home/ubuntu/tools/mempool-dumpster/collector/collector.go:21 +0x258
exit status 2
```
which points to `p.srcCntUnique[txIn.Source][txHash.Hex()] = true`

This is strange but can be avoided by checking initialization (https://github.com/0xJchen/mempool-dumpster/commit/eae0ceaba73b91202e546a3494fc87a00325a5b3):

```
	if p.srcCntUnique[txIn.Source] == nil {
		p.srcCntUnique[txIn.Source] = make(map[string]bool)
	}
```

**Comment by metachris** [comment]
great catch, thanks, fixed in https://github.com/flashbots/mempool-dumpster/commit/3185a8ed6438c0e0d4d312bf98bfee97e7264ea8
